## This file was auto-generated by CloudCoreo CLI
## This file was automatically generated using the CloudCoreo CLI
##
## This config.rb file exists to create and maintain services not related to compute.
## for example, a VPC might be maintained using:
##
## coreo_aws_vpc_vpc "my-vpc" do
##   action :sustain
##   cidr "12.0.0.0/16"
##   internet_gateway true
## end
##
# coreo_aws_vpc_vpc "${VPC_NAME}" do
#   action :find_or_create
#   cidr "${VPC_OCTETS}/16"
#   internet_gateway true
# end
# coreo_aws_vpc_routetable "${PUBLIC_ROUTE_NAME}" do
#   action :sustain
#   vpc "${VPC_NAME}"
#   routes [
#              { :from => "0.0.0.0/0", :to => "${VPC_NAME}", :type => :igw }
#         ]
#   number_of_tables 1
# end
# coreo_aws_vpc_subnet "${PUBLIC_SUBNET_NAME}" do
#   action :sustain
#   number_of_zones 3
#   percent_of_vpc_allocated 25
#   route_table "${PUBLIC_ROUTE_NAME}"
#   vpc "${VPC_NAME}"
#   map_public_ip_on_launch true
# end
# coreo_aws_vpc_routetable "${PRIVATE_ROUTE_NAME}" do
#   action :create
#   vpc "${VPC_NAME}"
#   number_of_tables 3
# end
# coreo_aws_vpc_subnet "${PRIVATE_SUBNET_NAME}" do
#   action :sustain
#   number_of_zones 3
#   percent_of_vpc_allocated 50
#   route_table "${PRIVATE_ROUTE_NAME}"
#   vpc "${VPC_NAME}"
# end
